<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>ELMapper.NET - the solution for automatic mapping of objects and collections. </Title>
    <Authors>Elvis Hodzic</Authors>
    <Description>ELMapper.NET - the solution for automatic mapping of objects and collections. It is necessary to define at least some properties from the source class to the destination with the same names in the source class. The Mapper works in two ways (object-to-object mapping and collection-to-collection mapping) using that work in asynchronous and synchronous modes.

These are the generic extension methods used (the suffix Async is for asynchronous methods):

- Task&lt;T_Destination&gt; MapObjectAsync&lt;T_Source, T_Destination&gt;(this T_Source objFrom, T_Destination? objTo=null)
- T_Destination MapObject&lt;T_Source, T_Destination&gt;(this T_Source objFrom, T_Destination? objTo = null)
- Task&lt;IEnumerable&lt;T_Destination&gt;&gt; MapIEnumerableAsync&lt;T_Source, T_Destination&gt;(this IEnumerable&lt;T_Source&gt; enumerableFrom, List&lt;T_Destination&gt;? listTo=null)
- IEnumerable&lt;T_Destination&gt; MapIEnumerable&lt;T_Source, T_Destination&gt;(this IEnumerable&lt;T_Source&gt; enumerableFrom, List&lt;T_Destination&gt;? listTo = null)
</Description>
    <PackageIcon>ELMapperNET.jpg</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>binding;mapping;dotnet;asp.net;dotnetcore</PackageTags>
    <Copyright>2026, Elvis Hodzic, e-mail: elvish91@hotmail.com</Copyright>
    <AssemblyVersion>8.0.0.1</AssemblyVersion>
    <FileVersion>8.0.0.1</FileVersion>
    <Version>8.0.2</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="image\ELMapperNET.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="image\ELMapperNET.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
